apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: kube-ops
  labels:
    k8s-app: prometheus
spec:
  selector:
    k8s-app: prometheus
  type: NodePort
  ports:
    - name: http
      port: 9090
      nodePort: 30267
      protocol: TCP
    - name: alert
      port: 9093
      nodePort: 30277
      protocol: TCP
